# Generated by Django 6.0.6 on 2026-06-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkylineMoving_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
